# Generated by Django 5.2.5 on 2025-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
