# Generated by Django 5.2.5 on 2025-08-17 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_fileitem_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='files.fileitem')),
            ],
        ),
    ]
