# Generated by Django 5.2.5 on 2025-08-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_filecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='category_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
