# Generated by Django 5.2.5 on 2025-08-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_filecontent_category_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontent',
            name='category_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
