# Generated by Django 5.2.5 on 2025-08-18 14:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_note_category_notecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecontent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
