# Generated by Django 5.2.5 on 2025-08-18 15:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_notecontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecontent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
